type: taco_net
name: taco_test_vs_${vs_type}
kwargs:
  encoder:
    hidden_dim: 100
    n_freqs: 4
    n_filters: 10
    n_rotations: 24
  decoder:
    kernel_size: 4
    n_filters: 10
    hidden_dim: 100
    n_outputs: 2