type: taco_net
name: taco_test_vs_${vs_type}
kwargs:
  encoder:
    # 
    cat_emb_feature: 'particle_type'
    cat_emb_dim_in: 7
    cat_emb_dim_out: 3
    hidden_dim_emb: 100
    out_dim_emb: 10
    # 
    hidden_dim_radial: 100
    n_freqs: 5
    n_filters: 15
    n_rotations: 45
  decoder:
    n_conv_blocks: 5
    n_conv_layers: 2
    n_conv_filters: ${model.kwargs.encoder.n_filters}
    kernel_size: 3
    hidden_dim: 100
    n_outputs: 2