defaults:
  - data@_global_: features
  - data@data_cfg: input_samples
  - data@gen_cfg: gen_config
  - _self_

dataset_name: ???

cache: False
shuffle_buffer_size: null # null to skip shuffling, otherwise number of samples to fill the cache with
batch_size:
  train: 125
  val: 125
  test: 1250

recompute_tau_type: ???
return_deeptau_score: ???
deeptau_columns:  # if return_deeptau_score=True, will return them in this order:
  - tau_byDeepTau2017v2p1VSeraw
  - tau_byDeepTau2017v2p1VSmuraw
  - tau_byDeepTau2017v2p1VSjetraw 
