defaults:
  - data@_global_: features
  - data@data_cfg: input_samples
  - data@gen_cfg: gen_config
  - _self_

vs_type: ???
dataset_name: ???

cache: False
shuffle_buffer_size: null # null to skip shuffling, otherwise number of samples to fill the cache with
batch_size:
  train: 125
  val: 125
  test: 1250
return_deeptau_score: ???
recompute_tau_type: ???