defaults:
  - data@_global_: features
  - data@data_cfg: input_samples
  - _self_

vs_type: ???
dataset_name: ???
n_samples_train: ??? # of each class
n_samples_val: ??? # of each class
train_batch_size: 250
val_batch_size: 1000
shuffle_buffer_size: ???