datasets_mix_name: ??? # to display in the title
datasets: 
  ???: ['tau']
  ???: ['${vs_type}']

vs_type: ???
n_per_split: 40000 # per class
n_splits: 5 # will split predictions into `n_splits` to get uncertainty estimate

path_to_mlflow: mlruns
deeptau_score_name: tau_byDeepTau2017v2p1VS${vs_type}raw
models: # DeepTau predictions will be taken from the last model in the list
  ???: [???, ???, ???, ???] # model name (to display in the legend) : [experiment_id, run_id, linestyle, alpha]

xlim: 
  jet: [0.3, 1.] 
  e: [0.5, 1.]
  mu: [0.95, 1.]
ylim: 
  jet: [0.00015, 1.01]
  e: [0.00001, 1.01]
  mu: [0.00015, 1.01]
auc_precision: 
  jet: 3
  e: 4
  mu: 4
figure_filename: roc_${vs_type} # will be saved in mlflow artifacts of the last model in "models"
