dataset_name: ???
dataset_type: ???
filename_prefix: ???

vs_type: ???
tau_type_to_node:
  tau: 0
  ${vs_type}: 1

path_to_mlflow: mlruns
experiment_id: ???
run_id: ???
checkpoint: ??? # null to load from "model" folder

output_filename: predictions

