
defaults:
  - model@model: ???
  - data@_global_: features
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

# datasets
vs_type: ???
dataset_name: ???
dataset_id: ???

# training
learning_rate: 0.0001
n_epochs: 1
