
defaults:
  - model@model: ???
  - data@_global_: features
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

# datasets
vs_type: ???
dataset_name: SM_v2 # to log to mlflow for bookkeeping
datasets: 
  train:
    SM_v2: # will take from "train" subfolder of this dataset
      file_prefix: ShuffleMergeSpectral_
      tau_types: ['tau', '${vs_type}']
  val:
    SM_v2: # will take from "val" subfolder of this dataset
      file_prefix: ShuffleMergeSpectral_
      tau_types: ['tau', '${vs_type}']  

# TF dataset formation
tf_dataset_cfg:
  shuffle_buffer_size: 40000 # null to not shuffle
  cache: null # null to not cache the training dataset
  train_batch_size: ???
  val_batch_size: ???
  classes: ["tau", "${vs_type}"] # will pick only those labels (in this order)

# training
learning_rate: 0.0001
n_epochs: 1

# gpu
gpu_id: 0
memory_limit: 8 # in Gb