
defaults:
  - model@model: ???
  - _self_

# input data
datasets:
  GluGluHToTauTau_M125: eventTuple_6
  TTToSemiLeptonic: eventTuple_80
  # DYJetsToLL_M-50-amcatnloFXFX_ext2: eventTuple_98
tree_name: taus

# train/val info
vs_type: jet
n_samples_train: 100000
n_samples_val: 30000
feature_names: ['r', 'theta', 'pt']
learning_rate: 0.001
batch_size: 100
n_epochs: 1
