
defaults:
  - model@model: ???
  - _self_

# mlflow
path_to_mlflow: mlruns
experiment_name: ???

# input data
datasets:
  tau:
    GluGluHToTauTau_M125: ['eventTuple_6']
  jet:
    TTToSemiLeptonic: ['eventTuple_80']
  e:
    DYJetsToLL_M-50-amcatnloFXFX_ext2: ['eventTuple_98', 'eventTuple_980', 'eventTuple_981']
  mu:
    DYJetsToLL_M-50-amcatnloFXFX_ext2: ['eventTuple_98', 'eventTuple_980', 'eventTuple_981']
tree_name: taus

# train/val info
vs_type: jet
n_samples_train: 80000
n_samples_val: 20000
feature_names: ['r', 'theta', 'pt', 'particle_type']
learning_rate: 0.001
batch_size: 100
n_epochs: 1
